services:
  whisper:
    container_name: whisper
    image: wyoming-whisper
    ports:
      - 10300:10300
    volumes:
      - ./models/:/data
    restart: unless-stopped
    command: --model ellisd/faster-whisper-large-v3-int8 --language nl  #--model medium-int8 --language nl
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]